// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteMessageByIDRequest struct {
	MessageID string `pathParam:"style=simple,explode=false,name=messageId"`
}

type DeleteMessageByIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
