// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DownloadDocumentByIDRequest struct {
	DocumentID string `pathParam:"style=simple,explode=false,name=documentId"`
}

type DownloadDocumentByIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// ok
	DownloadDocumentByID200ApplicationOctetStreamBinaryString []byte
}
