// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/pkg/models/shared"
)

type GetConversationByIDRequest struct {
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
}

type GetConversationByIDResponse struct {
	ContentType string
	// Conversation details
	Conversation *shared.Conversation
	StatusCode   int
	RawResponse  *http.Response
}
