// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetDocumentByIDRequest struct {
	DocumentID string `pathParam:"style=simple,explode=false,name=documentId"`
}

// GetDocumentByID200ApplicationJSON - ok
type GetDocumentByID200ApplicationJSON struct {
	ID *string `json:"Id,omitempty"`
}

type GetDocumentByIDResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// ok
	GetDocumentByID200ApplicationJSONObject *GetDocumentByID200ApplicationJSON
}
