// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/v2/pkg/models/shared"
)

type GetFolderByIDRequest struct {
	FolderID string `pathParam:"style=simple,explode=false,name=folderId"`
}

func (o *GetFolderByIDRequest) GetFolderID() string {
	if o == nil {
		return ""
	}
	return o.FolderID
}

type GetFolderByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// ok
	FolderListing *shared.FolderListing
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetFolderByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetFolderByIDResponse) GetFolderListing() *shared.FolderListing {
	if o == nil {
		return nil
	}
	return o.FolderListing
}

func (o *GetFolderByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetFolderByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
