// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/pkg/models/shared"
)

type GetFolderByIDRequest struct {
	FolderID string `pathParam:"style=simple,explode=false,name=folderId"`
}

type GetFolderByIDResponse struct {
	ContentType string
	// ok
	FolderListing *shared.FolderListing
	StatusCode    int
	RawResponse   *http.Response
}
