// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/pkg/models/shared"
)

type GetMessageByIDRequest struct {
	MessageID string `pathParam:"style=simple,explode=false,name=messageId"`
}

type GetMessageByIDResponse struct {
	ContentType string
	// ok
	Message     *shared.Message
	StatusCode  int
	RawResponse *http.Response
}
