// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/pkg/models/shared"
)

type GetSpacesResponse struct {
	ContentType string
	// ok
	SpaceList   *shared.SpaceList
	StatusCode  int
	RawResponse *http.Response
}
