// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/v3/pkg/models/shared"
)

type ReplyToConversationRequest struct {
	Reply          *shared.Reply `request:"mediaType=application/json"`
	ConversationID string        `pathParam:"style=simple,explode=false,name=conversationId"`
}

func (o *ReplyToConversationRequest) GetReply() *shared.Reply {
	if o == nil {
		return nil
	}
	return o.Reply
}

func (o *ReplyToConversationRequest) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}

type ReplyToConversationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReplyToConversationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReplyToConversationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReplyToConversationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
