// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/pkg/models/shared"
)

type ReplyToConversationRequest struct {
	Reply          *shared.Reply `request:"mediaType=application/json"`
	ConversationID string        `pathParam:"style=simple,explode=false,name=conversationId"`
}

type ReplyToConversationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
