// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"tlan-trust-spaces/pkg/models/shared"
)

type StartConversationRequest struct {
	ConversationStart *shared.ConversationStart `request:"mediaType=application/json"`
	SpaceID           string                    `pathParam:"style=simple,explode=false,name=spaceId"`
}

type StartConversationResponse struct {
	ContentType string
	// ok
	ConversationStartResponse *shared.ConversationStartResponse
	StatusCode                int
	RawResponse               *http.Response
}
