// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type UploadDocumentRequestBodyAttributes struct {
	FolderID string `json:"folderId"`
}

type UploadDocumentRequestBodyDocument struct {
	Content  []byte `multipartForm:"content"`
	Document string `multipartForm:"name=document"`
}

type UploadDocumentRequestBody1 struct {
	Attributes UploadDocumentRequestBodyAttributes `multipartForm:"name=attributes,json"`
	Document   UploadDocumentRequestBodyDocument   `multipartForm:"file"`
}

// UploadDocument201ApplicationJSON - Upload successful
type UploadDocument201ApplicationJSON struct {
	DocumentID *string `json:"documentId,omitempty"`
}

type UploadDocumentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Upload successful
	UploadDocument201ApplicationJSONObject *UploadDocument201ApplicationJSON
}
