// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConversationStartDocuments struct {
	ID *string `json:"id,omitempty"`
}

type ConversationStart struct {
	Documents  []ConversationStartDocuments `json:"documents,omitempty"`
	Message    *string                      `json:"message,omitempty"`
	Recipients []string                     `json:"recipients"`
	Subject    string                       `json:"subject"`
}
