// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Conversation - Conversation details
type Conversation struct {
	CreatedDate     time.Time `json:"createdDate"`
	ID              string    `json:"id"`
	LastMessageDate time.Time `json:"lastMessageDate"`
	Messages        []Message `json:"messages"`
	Read            bool      `json:"read"`
	Subject         string    `json:"subject"`
}
