// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConversationStartResponse struct {
	ConversationID string `json:"conversationId"`
}

func (o *ConversationStartResponse) GetConversationID() string {
	if o == nil {
		return ""
	}
	return o.ConversationID
}
