// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConversationStartResponse - ok
type ConversationStartResponse struct {
	ConversationID string `json:"conversationId"`
}
