// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ConversationListItem struct {
	CreatedDate     time.Time `json:"createdDate"`
	ID              string    `json:"id"`
	LastMessageDate time.Time `json:"lastMessageDate"`
	Read            bool      `json:"read"`
	Subject         string    `json:"subject"`
}
