// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ConversationListItem struct {
	CreatedDate     time.Time `json:"createdDate"`
	ID              string    `json:"id"`
	LastMessageDate time.Time `json:"lastMessageDate"`
	Read            bool      `json:"read"`
	Subject         string    `json:"subject"`
}

func (o *ConversationListItem) GetCreatedDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedDate
}

func (o *ConversationListItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ConversationListItem) GetLastMessageDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.LastMessageDate
}

func (o *ConversationListItem) GetRead() bool {
	if o == nil {
		return false
	}
	return o.Read
}

func (o *ConversationListItem) GetSubject() string {
	if o == nil {
		return ""
	}
	return o.Subject
}
