// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FolderListingFile struct {
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name,omitempty"`
	SizeInBytes *int64  `json:"sizeInBytes,omitempty"`
}
