// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FolderListing - ok
type FolderListing struct {
	Files   []FolderListingFile   `json:"files"`
	Folders []FolderListingFolder `json:"folders"`
	ID      string                `json:"id"`
	Name    string                `json:"name"`
	Parent  string                `json:"parent"`
	SpaceID string                `json:"spaceId"`
}
