// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Message - ok
type Message struct {
	ConversationID string            `json:"conversationId"`
	CreatedDate    time.Time         `json:"createdDate"`
	Documents      []MessageDocument `json:"documents"`
	ID             string            `json:"id"`
	Message        string            `json:"message"`
	Sender         User              `json:"sender"`
}
