// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MessageDocument struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (o *MessageDocument) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *MessageDocument) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
