// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Reply struct {
	Documents []MessageDocument `json:"documents,omitempty"`
	Message   *string           `json:"message,omitempty"`
}
