// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SpaceType string

const (
	SpaceTypePersonal SpaceType = "personal"
	SpaceTypeTeam     SpaceType = "team"
)

func (e SpaceType) ToPointer() *SpaceType {
	return &e
}

func (e *SpaceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "personal":
		fallthrough
	case "team":
		*e = SpaceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SpaceType: %v", v)
	}
}

type Space struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	RootFolderID string    `json:"rootFolderId"`
	SpaceType    SpaceType `json:"spaceType"`
}

func (o *Space) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Space) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Space) GetRootFolderID() string {
	if o == nil {
		return ""
	}
	return o.RootFolderID
}

func (o *Space) GetSpaceType() SpaceType {
	if o == nil {
		return SpaceType("")
	}
	return o.SpaceType
}
