// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SpaceList - ok
type SpaceList struct {
	Spaces []Space `json:"spaces"`
}

func (o *SpaceList) GetSpaces() []Space {
	if o == nil {
		return []Space{}
	}
	return o.Spaces
}
